/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./utils/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    fontSize: {
      xs: "var(--step--2)",
      sm: "var(--step--1)",
      base: "var(--step-0)",
      lg: "var(--step-1)",
      xl: "var(--step-2)",
      "2xl": "var(--step-3)",
      "3xl": "var(--step-4)",
      "4xl": "var(--step-5)",
    },
    spacing: {
      0: "0",
      0.5: "var(--space-7xs)",
      1: "var(--space-6xs)",
      1.5: "var(--space-5xs)",
      2: "var(--space-4xs)",
      2.5: "var(--space-3xs)",
      3: "var(--space-2xs)",
      3.5: "var(--space-xs)",
      4: "var(--space-s)",
      5: "var(--space-m)",
      6: "var(--space-l)",
      7: "var(--space-xl)",
      8: "var(--space-2xl)",
      9: "var(--space-3xl)",
      10: "var(--space-4xl)",
      11: "var(--space-5xl)",
      12: "var(--space-6xl)",
      14: "var(--space-7xl)",
      16: "var(--space-8xl)",
      20: "var(--space-9xl)",
      24: "var(--space-10xl)",
      28: "var(--space-11xl)",
      32: "var(--space-12xl)",
      36: "var(--space-13xl)",
      40: "var(--space-14xl)",
      44: "var(--space-15xl)",
      48: "var(--space-16xl)",
      52: "var(--space-17xl)",
      56: "var(--space-18xl)",
      60: "var(--space-19xl)",
      64: "var(--space-20xl)",
      72: "var(--space-21xl)",
      80: "var(--space-22xl)",
      96: "var(--space-23xl)",
      px: "1px",
    },
  },
  plugins: [],
};
